export const POST_TEACHER_LOGIN_REQUEST = 'POST_TEACHER_LOGIN_REQUEST';
export const POST_TEACHER_LOGIN_SUCCESS = 'POST_TEACHER_LOGIN_SUCCESS';
export const POST_TEACHER_LOGIN_FAILURE = 'POST_TEACHER_LOGIN_FAILURE';
export const POST_LOGOUT = 'POST_LOGOUT';
