export const FETCH_SCORE = 'FETCH_SCORE'
export const FETCH_SCORE_REQUEST = 'FETCH_SCORE_REQUEST'
export const FETCH_SCORE_SUCCESS = 'FETCH_SCORE_SUCCESS'
export const FETCH_SCORE_FAILURE = 'FETCH_SCORE_FAILURE'