export const FETCH_VOA_LIST = 'FETCH_VOA_LIST';
export const FETCH_VOA_LIST_SUCCESS = 'FETCH_VOA_LIST_SUCCESS';
export const FETCH_VOA_LIST_FAILURE = 'FETCH_VOA_LIST_FAILURE';

export const FETCH_VOA_DETAIL = 'FETCH_VOA_DETAIL';
export const FETCH_VOA_DETAIL_SUCCESS = 'FETCH_VOA_DETAIL_SUCCESS';
export const FETCH_VOA_DETAIL_FAILURE = 'FETCH_VOA_DETAIL_FAILURE';


