
export const FETCH_ASSIGNMENT_REQUEST = 'FETCH_ASSIGNMENT_REQUEST';
export const FETCH_ASSIGNMENT_SUCCESS = 'FETCH_ASSIGNMENT_SUCCESS';
export const FETCH_ASSIGNMENT_FAILURE = 'FETCH_ASSIGNMENT_FAILURE';

export const FETCH_ASSIGNMENTS_MIX4_REQUEST    = 'FETCH_ASSIGNMENTS_MIX4_REQUEST';
export const FETCH_ASSIGNMENTS_MIX4_SUCCESS    = 'FETCH_ASSIGNMENTS_MIX4_SUCCESS';
export const FETCH_ASSIGNMENTS_MIX4_FAILURE    = 'FETCH_ASSIGNMENTS_MIX4_FAILURE';
