export const FETCH_CLASS = 'FETCH_CLASS';
export const FETCH_CLASS_REQUEST = 'FETCH_CLASS_REQUEST';
export const FETCH_CLASS_SUCCESS = 'FETCH_CLASS_SUCCESS';
export const FETCH_CLASS_FAILURE = 'FETCH_CLASS_FAILURE';

export const SAVE_SELECTED_CLASS = 'SAVE_SELECTED_CLASS';
export const TOGGLE_DOING_LATEST_ASSIGNMENTS = 'TOGGLE_DOING_LATEST_ASSIGNMENTS'