export const CHANGE_TYPE = "CHANGE_TYPE";
export const AUTHENTICATION = "AUTHENTICATION";

export const CHECK_LOCAL_STORAGE = 'CHECK_LOCAL_STORAGE';
export const CHECK_LOCAL_STORAGE_DONE = 'CHECK_LOCAL_STORAGE_DONE';

export const GET_QUESTION_API_REQUEST = 'GET_QUESTION_API_REQUEST';
export const GET_QUESTION_API_REQUEST_DONE = 'GET_QUESTION_API_REQUEST_DONE';

export const GET_QUESTIONBYID_API_REQUEST = 'GET_QUESTIONBYID_API_REQUEST';
export const GET_QUESTIONBYID_API_REQUEST_DONE = 'GET_QUESTIONBYID_API_REQUEST_DONE';

export const UPDATE_QUESTION_API_REQUEST = 'UPDATE_QUESTION_API_REQUEST';
export const UPDATE_QUESTION_API_REQUEST_DONE = 'UPDATE_QUESTION_API_REQUEST_DONE';